### ISSUE TITLE
Payment Failure

### ISSUE THREAD

**Issue by dhushandhansd** [cyberboysumanjay/upayi#2]
Hey Team,
      The App is Great, but there is a Bug to be resolved.
The Payment is Failed with an Error Message of "You've exceeded the bank limit for this payment' on an Payment of Rs.1/- only.
Other Scripts are working fine but there comes an error on the payment Section.
Please resolve this Issue,

Regards,
Shree Dhushandhan

**Comment by cyberboysumanjay** [comment]
Hi @dhushandhansd,
Thanks for using this service.
Regarding the issue you're facing you need to use business UPI ID according to new guidelines of NPCI otherwise it can be flagged.

I'm using my GPay Business UPI Id in the donate button and it's working fine for me. You can try sending a lower amount to that UPI and it'll not give you any error.

**Comment by dhushandhansd** [comment]
Thanks @cyberboysumanjay for the Heads up, Let me try in that Fashion.
On the other Hand, the App is Great, Keep doing.  👍👍
